"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Search, ChevronDown, BookOpen, Zap, Shield,
  MessageCircle, ExternalLink, LifeBuoy, ArrowRight,
  CheckSquare, Folder, Users, Flame, Sparkles,
} from "lucide-react";

type FAQ = {
  q: string;
  a: string;
};

type Section = {
  icon: any;
  label: string;
  color: string;
  faqs: FAQ[];
};

const helpSections: Section[] = [
  {
    icon: Zap,
    label: "Getting Started",
    color: "#f59e0b",
    faqs: [
      {
        q: "How do I create my first task?",
        a: "Head to the Tasks page from the sidebar. Type your task in the input field at the top and press Enter or click Add. Your task will appear instantly in the list below.",
      },
      {
        q: "How does the AI Assistant work?",
        a: "GrowthX uses a powerful AI backend to answer questions, suggest next actions, and give you productivity insights. Open the AI page from the sidebar and start chatting — it remembers the context of your conversation.",
      },
      {
        q: "Can I use GrowthX on mobile?",
        a: "Yes. GrowthX is fully responsive. On mobile, the sidebar becomes a slide-out drawer accessible from the hamburger menu in the top bar.",
      },
      {
        q: "How do I sign in?",
        a: "GrowthX uses Clerk for authentication. Click 'Continue with Clerk' on the welcome screen and sign in with your Google account, email, or any supported OAuth provider.",
      },
    ],
  },
  {
    icon: CheckSquare,
    label: "Tasks & Projects",
    color: "#34d399",
    faqs: [
      {
        q: "How do I mark a task as done?",
        a: "Click the circle icon on the left of any task row to toggle it between todo and done. Completed tasks show a strikethrough and a green checkmark timestamp.",
      },
      {
        q: "Can I filter tasks?",
        a: "Yes. Use the filter pills at the top of the Tasks page to switch between All, Todo, and Done views. You can also search tasks by name using the search input.",
      },
      {
        q: "How do I update project progress?",
        a: "Open the Projects page, find your project card, and click the 'Update progress' button. Enter a number between 0–100 and hit the green checkmark to save.",
      },
      {
        q: "What is the tech stack field for?",
        a: "When creating a project, the tech stack field lets you tag the technologies used (e.g. 'Next.js, Tailwind, MongoDB'). These render as chips on the project card.",
      },
    ],
  },
  {
    icon: Users,
    label: "Clients & Leads",
    color: "#ec4899",
    faqs: [
      {
        q: "What's the difference between a Client and a Lead?",
        a: "Leads are potential customers you're pursuing — they have a pipeline status (New, Contacted, Converted, Lost). Clients are confirmed relationships you're actively managing.",
      },
      {
        q: "How do I update a lead's status?",
        a: "On the Leads page, use the status dropdown directly in the table row (desktop) or in the card (mobile). Changes save instantly to the database.",
      },
      {
        q: "Can I message a lead via WhatsApp?",
        a: "Yes. If you've saved a phone number for the lead, click the 'WA' or 'WhatsApp' button to open a WhatsApp chat pre-filled with that number.",
      },
    ],
  },
  {
    icon: Sparkles,
    label: "AI Features",
    color: "#a78bfa",
    faqs: [
      {
        q: "What does the AI Productivity Score mean?",
        a: "The score on your Dashboard is generated by the AI based on your task completion rate, active projects, and recent activity. It's a motivational signal, not a strict metric.",
      },
      {
        q: "How accurate are the AI Priorities and Suggestions?",
        a: "They're generated from a snapshot of your workspace data. The more data you have (tasks, projects, jobs, clients), the more relevant the suggestions become.",
      },
      {
        q: "Can the AI see my private data?",
        a: "The AI only has access to data within your GrowthX workspace and only while generating a response. No conversation history is stored beyond your current session.",
      },
    ],
  },
  {
    icon: Shield,
    label: "Account & Billing",
    color: "#60a5fa",
    faqs: [
      {
        q: "How do I change my display name or email?",
        a: "Go to Profile & Settings from the sidebar. Edit your name and email in the 'Your Details' section and click Save Changes.",
      },
      {
        q: "How do I delete my account?",
        a: "Click 'Manage Account' on your Profile page to open the Clerk account portal. From there you can delete your account and all associated data.",
      },
      {
        q: "Is GrowthX free to use?",
        a: "GrowthX currently offers a Pro plan. Contact support if you have billing questions or need to manage your subscription.",
      },
    ],
  },
];

const quickLinks = [
  { icon: BookOpen, label: "Documentation", sub: "Full API & feature docs", color: "#f59e0b" },
  { icon: MessageCircle, label: "Live Chat", sub: "Talk to support now", color: "#34d399" },
  { icon: LifeBuoy, label: "Status Page", sub: "Uptime & incidents", color: "#60a5fa" },
  { icon: ExternalLink, label: "Changelog", sub: "What's new in GrowthX", color: "#a78bfa" },
];

function AccordionItem({ faq, index }: { faq: FAQ; index: number }) {
  const [open, setOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04 }}
      className="overflow-hidden rounded-xl transition-all"
      style={{
        background: open ? "rgba(255,255,255,0.05)" : "rgba(255,255,255,0.02)",
        border: `1px solid ${open ? "rgba(255,255,255,0.1)" : "rgba(255,255,255,0.06)"}`,
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 text-left gap-4"
      >
        <span className="text-[13.5px] font-medium text-white">{faq.q}</span>
        <motion.div
          animate={{ rotate: open ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          className="flex-shrink-0"
        >
          <ChevronDown size={15} className="text-gray-500" />
        </motion.div>
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
          >
            <div className="px-5 pb-4">
              <div className="h-px mb-4" style={{ background: "rgba(255,255,255,0.06)" }} />
              <p className="text-sm text-gray-400 leading-relaxed">{faq.a}</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function HelpCenterPage() {
  const [search, setSearch] = useState("");
  const [activeSection, setActiveSection] = useState<string | null>(null);

  const allFaqs = helpSections.flatMap((s) =>
    s.faqs.map((f) => ({ ...f, sectionLabel: s.label, sectionColor: s.color }))
  );

  const searchResults = search.trim().length > 1
    ? allFaqs.filter(
        (f) =>
          f.q.toLowerCase().includes(search.toLowerCase()) ||
          f.a.toLowerCase().includes(search.toLowerCase())
      )
    : null;

  const visibleSections = activeSection
    ? helpSections.filter((s) => s.label === activeSection)
    : helpSections;

  return (
    <div
      className="min-h-screen text-white"
      style={{
        fontFamily: "'DM Sans', system-ui, sans-serif",
        background: "linear-gradient(160deg, #080808 0%, #0f0f13 50%, #0a0a10 100%)",
      }}
    >
      {/* Ambient glows */}
      <div className="fixed top-0 right-0 w-[500px] h-[500px] pointer-events-none"
        style={{ background: "radial-gradient(circle, rgba(245,158,11,0.05) 0%, transparent 70%)" }} />
      <div className="fixed bottom-0 left-0 w-[400px] h-[400px] pointer-events-none"
        style={{ background: "radial-gradient(circle, rgba(96,165,250,0.04) 0%, transparent 70%)" }} />

      <div className="max-w-3xl mx-auto px-4 py-8 pb-24">

        {/* Header */}
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
          <p className="text-[11px] tracking-[0.25em] uppercase text-gray-600 font-semibold mb-2">Support</p>
          <h1 className="text-3xl font-black tracking-tight mb-2">Help Center</h1>
          <p className="text-gray-500 text-sm">Find answers, docs, and support for GrowthX.</p>
        </motion.div>

        {/* Search bar */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.08 }}
          className="relative mb-8"
        >
          <Search size={15} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-600" />
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search help articles…"
            className="w-full pl-11 pr-4 py-4 rounded-2xl text-sm outline-none transition-all"
            style={{
              background: "rgba(255,255,255,0.05)",
              border: "1px solid rgba(255,255,255,0.09)",
              color: "white",
            }}
            onFocus={(e) => (e.target.style.borderColor = "rgba(245,158,11,0.4)")}
            onBlur={(e) => (e.target.style.borderColor = "rgba(255,255,255,0.09)")}
          />
        </motion.div>

        {/* Search results */}
        {searchResults !== null && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="mb-8"
          >
            <p className="text-[11px] text-gray-600 uppercase tracking-widest font-semibold mb-3 px-1">
              {searchResults.length} result{searchResults.length !== 1 ? "s" : ""} for "{search}"
            </p>
            {searchResults.length === 0 ? (
              <div className="text-center py-12 text-gray-600">
                <Search size={28} className="mx-auto mb-3 opacity-30" />
                <p className="text-sm">No articles found. Try different keywords.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {searchResults.map((f, i) => (
                  <div key={i} className="rounded-xl px-5 py-4"
                    style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}>
                    <p className="text-[10px] uppercase tracking-widest font-semibold mb-1.5"
                      style={{ color: f.sectionColor }}>{f.sectionLabel}</p>
                    <p className="text-sm font-medium text-white mb-1">{f.q}</p>
                    <p className="text-xs text-gray-500 leading-relaxed line-clamp-2">{f.a}</p>
                  </div>
                ))}
              </div>
            )}
          </motion.div>
        )}

        {/* Quick links */}
        {!searchResults && (
          <>
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.12 }}
              className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8"
            >
              {quickLinks.map((link, i) => {
                const Icon = link.icon;
                return (
                  <motion.button
                    key={link.label}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.15 + i * 0.06 }}
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.97 }}
                    className="flex flex-col items-start p-4 rounded-2xl text-left transition-all group"
                    style={{
                      background: `${link.color}0d`,
                      border: `1px solid ${link.color}20`,
                    }}
                  >
                    <div className="w-8 h-8 rounded-xl flex items-center justify-center mb-3"
                      style={{ background: `${link.color}18` }}>
                      <Icon size={15} style={{ color: link.color }} />
                    </div>
                    <p className="text-xs font-bold text-white leading-none mb-1">{link.label}</p>
                    <p className="text-[10px] text-gray-600">{link.sub}</p>
                    <ArrowRight size={11} className="mt-2 opacity-0 group-hover:opacity-100 transition-opacity"
                      style={{ color: link.color }} />
                  </motion.button>
                );
              })}
            </motion.div>

            {/* Section filter pills */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
              className="flex flex-wrap gap-2 mb-6"
            >
              <button
                onClick={() => setActiveSection(null)}
                className="px-3 py-1.5 rounded-full text-xs font-semibold transition-all"
                style={{
                  background: !activeSection ? "rgba(255,255,255,0.1)" : "rgba(255,255,255,0.04)",
                  border: `1px solid ${!activeSection ? "rgba(255,255,255,0.2)" : "rgba(255,255,255,0.07)"}`,
                  color: !activeSection ? "white" : "#555",
                }}
              >
                All topics
              </button>
              {helpSections.map((s) => {
                const Icon = s.icon;
                const isActive = activeSection === s.label;
                return (
                  <button
                    key={s.label}
                    onClick={() => setActiveSection(isActive ? null : s.label)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-semibold transition-all"
                    style={{
                      background: isActive ? `${s.color}14` : "rgba(255,255,255,0.04)",
                      border: `1px solid ${isActive ? `${s.color}30` : "rgba(255,255,255,0.07)"}`,
                      color: isActive ? s.color : "#555",
                    }}
                  >
                    <Icon size={11} />
                    {s.label}
                  </button>
                );
              })}
            </motion.div>

            {/* FAQ sections */}
            <div className="space-y-8">
              {visibleSections.map((section, si) => {
                const Icon = section.icon;
                return (
                  <motion.div
                    key={section.label}
                    initial={{ opacity: 0, y: 14 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.22 + si * 0.07 }}
                  >
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0"
                        style={{ background: `${section.color}18`, border: `1px solid ${section.color}25` }}>
                        <Icon size={15} style={{ color: section.color }} />
                      </div>
                      <p className="text-sm font-bold text-white">{section.label}</p>
                      <div className="flex-1 h-px" style={{ background: "rgba(255,255,255,0.05)" }} />
                      <span className="text-[10px] text-gray-600">{section.faqs.length} articles</span>
                    </div>
                    <div className="space-y-2">
                      {section.faqs.map((faq, fi) => (
                        <AccordionItem key={fi} faq={faq} index={fi} />
                      ))}
                    </div>
                  </motion.div>
                );
              })}
            </div>

            {/* Bottom CTA */}
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
              className="mt-12 rounded-2xl p-6 text-center relative overflow-hidden"
              style={{
                background: "linear-gradient(135deg, rgba(245,158,11,0.08), rgba(96,165,250,0.06))",
                border: "1px solid rgba(245,158,11,0.15)",
              }}
            >
              <div className="absolute top-0 left-0 right-0 h-px"
                style={{ background: "linear-gradient(90deg, transparent, rgba(245,158,11,0.3), transparent)" }} />
              <MessageCircle size={24} className="mx-auto mb-3" style={{ color: "#f59e0b" }} />
              <p className="font-bold text-white mb-1">Still need help?</p>
              <p className="text-sm text-gray-500 mb-4">Our support team usually replies within a few hours.</p>
              <motion.button
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                className="px-6 py-2.5 rounded-xl text-sm font-semibold transition-all"
                style={{
                  background: "rgba(245,158,11,0.15)",
                  border: "1px solid rgba(245,158,11,0.3)",
                  color: "#fcd34d",
                }}
              >
                Contact Support
              </motion.button>
            </motion.div>
          </>
        )}
      </div>
    </div>
  );
}